tap "homebrew/core"
tap "homebrew/cask-versions"
tap "homebrew/cask"
tap "homebrew/bundle"
cask "osxfuse"
cask "java"
cask "calibre"
cask "android-file-transfer"
cask "adium"
brew "youtube-dl"
brew "xhyve"
brew "wget"
brew "webp"
brew "sqlcipher"
brew "s3cmd"
brew "readline"
brew "qt"
brew "qrencode"
brew "pth"
brew "pkg-config"
brew "opus"
brew "openssl@1.1"
brew "oniguruma"
brew "node"
brew "mp4v2"
brew "maven"
brew "mad"
brew "libvpx"
brew "libvorbis"
brew "libusb-compat"
brew "libtool"
brew "libsodium"
brew "libksba"
brew "libexif"
brew "libcue"
brew "libao"
brew "lame"
brew "jq"
brew "jack"
brew "hub"
brew "gradle"
brew "gnupg"
brew "git"
brew "gcc"
brew "gauge"
brew "flac"
brew "ffmpeg"
brew "faad2"
brew "ext4fuse"
brew "coreutils"
brew "cmus"
brew "cmake"
brew "check"
brew "bash-completion@2"
brew "awscli"
brew "automake"
brew "autoconf"
brew "ant"
# cask "yacreader"
# cask "xquartz"
# cask "vlc"
# cask "virtualbox"
# cask "vagrant"
# cask "tunnelblick"
# cask "sublime-text3"
# cask "sublime-text"
# cask "slack"
# cask "skype"
# cask "skitch"
# cask "seashore"
# cask "rar"
# cask "quicksilver"
# cask "postman"
# cask "p4v"
# cask "p4merge"
# cask "nylas-n1"
# cask "libreoffice"
# cask "karabiner"
# cask "iterm2"
# cask "intellij-idea"
# cask "inkscape"
# cask "google-chrome"
# cask "gimp"
# cask "flux"
# cask "firefox"
# cask "etcher"
# cask "dropbox"
# cask "docker"
# cask "copyq"
# cask "blender"
